# src/aegis/api/schemas/clinical.py
"""
API schemas for clinical note ingestion (POST /api/v1/clinical-notes).

These are HTTP boundary DTOs, not domain models: ``ClinicalNoteIngestionRequest``
translates an external caller's submission into
``aegis.models.workflow_commands.ClinicalNoteSubmission``, and
``ClinicalNoteIngestionResponse`` translates the terminal/interrupted
``AegisWorkflowState`` produced by the LangGraph workflow back into
something an HTTP caller can act on. Domain models (``ClinicalNote``,
``CodingRecommendation``, ``ClinicalDecision``, ...) are never returned
directly from the router.
"""

from __future__ import annotations

from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field

from aegis.models.base import ICDCode


class ClinicalNoteIngestionRequest(BaseModel):
    """External submission of a clinical note for AI-assisted ICD-11 coding."""

    patient_id: UUID
    content_reference: str = Field(min_length=1)


class ClinicalNoteIngestionWithContentRequest(BaseModel):
    """
    External submission of *raw* clinical note content, for a caller with no
    pre-existing ``content_reference``.

    ``ClinicalNoteIngestionRequest`` above requires a caller to already hold
    a reference into previously-stored content -- it never accepts note text
    itself (see ``runtime_domain_contracts/clinical_note.md``: content_reference
    is an opaque pointer, not inline text). This request is the ingestion
    boundary that closes that gap: the router mints a fresh
    ``content_reference``, stores ``note_text`` through the content
    repository, and only then starts the workflow -- see
    ``aegis.api.routers.clinical.ingest_clinical_note``.
    """

    patient_id: UUID
    note_text: str = Field(min_length=1)


class WorkflowStatus(str, Enum):
    """Terminal state of a single workflow invocation, as observed by the router."""

    PENDING_REVIEW = "pending_review"
    COMPLETED = "completed"


class ApprovedICDCodeResponse(BaseModel):
    icd_code: ICDCode
    disposition: str


class ClinicalNoteIngestionResponse(BaseModel):
    """
    Result of submitting a clinical note into the AEGIS workflow.

    ``workflow_id`` is the LangGraph checkpoint thread id -- the handle
    a caller needs to resume this run past human review in a later
    slice. It is generated by the router itself, ahead of graph
    invocation (the graph contract has no notion of a workflow id), and
    is always equal to ``case_id``: both are the same canonical identity
    the router assigns before invoking the graph, which
    ``ClinicalNoteService`` in turn assigns to the resulting
    ``ClinicalNote`` rather than generating its own.

    ``status == PENDING_REVIEW`` means the workflow suspended at the
    ``human_review_pending`` interrupt; ``decision_id`` and
    ``approved_icd_codes`` are absent because no ``ClinicalDecision``
    exists yet. ``status == COMPLETED`` means the workflow completed
    with a ``ClinicalDecision`` already available; both fields are
    present. Why a decision was already available (e.g. a cache hit)
    is an internal workflow detail this schema does not surface.
    """

    workflow_id: UUID
    case_id: UUID
    status: WorkflowStatus
    decision_id: UUID | None = None
    approved_icd_codes: list[ApprovedICDCodeResponse] | None = None
